version: '2'
services:
    labofapapi-app:
        image: labofapapi
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://labofapapi-postgresql:5432/labofapapi
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    labofapapi-postgresql:
        extends:
            file: postgresql.yml
            service: labofapapi-postgresql
